find_package(Doxygen REQUIRED)
set(DOXYGEN_OUT "${PROJECT_BINARY_DIR}/docs/Doxyfile")
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/docs")
find_program(INI_DOT_EXECUTABLE dot)
set(INI_HAVE_DOT NO)
if(INI_DOT_EXECUTABLE)
    set(INI_HAVE_DOT YES)
endif()
configure_file("${PROJECT_SOURCE_DIR}/docs/Doxyfile.in" "${DOXYGEN_OUT}" @ONLY)
add_custom_target(docs COMMAND "${DOXYGEN_EXECUTABLE}" "${DOXYGEN_OUT}"
    WORKING_DIRECTORY "${PROJECT_BINARY_DIR}/docs" COMMENT "Building documentation")
