cmake_minimum_required(VERSION 4.0...4.4)
if(NOT DEFINED PROJECT_SOURCE_DIR OR NOT DEFINED PROJECT_BINARY_DIR)
    message(FATAL_ERROR "Set PROJECT_SOURCE_DIR and PROJECT_BINARY_DIR")
endif()
file(READ "${PROJECT_SOURCE_DIR}/CMakeLists.txt" project_file)
string(REGEX MATCH "project\\([^)]*VERSION[ \t\r\n]+([0-9.]+)" version_match "${project_file}")
if(NOT version_match)
    message(FATAL_ERROR "Could not find project version in CMakeLists.txt")
endif()
set(PROJECT_VERSION "${CMAKE_MATCH_1}")
set(PROJECT_NAME ini_manager)
find_program(DOXYGEN_EXECUTABLE doxygen REQUIRED)
file(MAKE_DIRECTORY "${PROJECT_BINARY_DIR}/docs")
find_program(INI_DOT_EXECUTABLE dot)
set(INI_HAVE_DOT NO)
if(INI_DOT_EXECUTABLE)
    set(INI_HAVE_DOT YES)
endif()
configure_file("${PROJECT_SOURCE_DIR}/docs/Doxyfile.in" "${PROJECT_BINARY_DIR}/docs/Doxyfile" @ONLY)
execute_process(COMMAND "${DOXYGEN_EXECUTABLE}" "${PROJECT_BINARY_DIR}/docs/Doxyfile"
    WORKING_DIRECTORY "${PROJECT_BINARY_DIR}/docs" RESULT_VARIABLE result)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "Doxygen failed: ${result}")
endif()
