cmake_minimum_required(VERSION 4.0...4.4)
if(NOT TIDY_COMMAND)
    set(TIDY_COMMAND clang-tidy)
endif()
if(NOT EXISTS "${BINARY_DIR}/compile_commands.json")
    message(FATAL_ERROR "tidy-check needs a Clang build with CMAKE_EXPORT_COMPILE_COMMANDS=ON")
endif()
file(READ "${BINARY_DIR}/compile_commands.json" database)
string(JSON count LENGTH "${database}")
math(EXPR last "${count} - 1")
set(sources)
foreach(index RANGE 0 ${last})
    string(JSON source GET "${database}" ${index} file)
    cmake_path(IS_PREFIX SOURCE_DIR "${source}" NORMALIZE is_project)
    if(is_project AND NOT source MATCHES "/(build|_deps)/")
        list(APPEND sources "${source}")
    endif()
endforeach()
list(REMOVE_DUPLICATES sources)
set(failed OFF)
foreach(source IN LISTS sources)
    message(STATUS "clang-tidy: ${source}")
    execute_process(COMMAND "${TIDY_COMMAND}" "${source}" -p "${BINARY_DIR}"
        "--header-filter=${SOURCE_DIR}/(include|example|test)/.*"
        WORKING_DIRECTORY "${SOURCE_DIR}" RESULT_VARIABLE result)
    if(NOT result EQUAL 0)
        set(failed ON)
    endif()
endforeach()
if(failed)
    message(FATAL_ERROR "clang-tidy reported errors; see diagnostics above")
endif()
